### PR TITLE
Rails 6

### PR DESCRIPTION
**Pull request by ghiculescu**
- Remove upper bound on `railties` dep so you can use this with Rails 6
- Develop against latest Ruby & Rails

Fixes https://github.com/onomojo/i18n-country-translations/issues/51

### CODE REVIEW

**Comment by markets** [comment]
Thanks @ghiculescu 👌  

I'm just digging into the same issue and this branch works fine for me under Rails 6! @onomojo any plan to release a new version with that? Thanks a lot in advanace 👍

**Comment by AlexLarra** [comment]
Works perfectly @ghiculescu :ok_hand:

**Comment by onomojo** [comment]
Thanks for the PR!

**Comment by shawjb** [comment]
:+1:

**Pull request merged**
